### ISSUE TITLE
Package zendframework/zend-text is abandoned

### ISSUE THREAD

**Issue by Pasqualle** [viossat/arraytotexttable#4]
Composer gives the following warnings:
Package zendframework/zend-servicemanager is abandoned, you should avoid using it. Use laminas/laminas-servicemanager instead.
Package zendframework/zend-text is abandoned, you should avoid using it. Use laminas/laminas-text instead.

**Comment by viossat** [comment]
Thanks for reporting, please upgrade to 1.0.8
